modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="vannila_expansion_m"
version="Beta 1.1.1"
displayName="M's Vanilla Expansion"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="IkBenPro1607"
description='''
Adds many cool items!
'''

[[dependencies.vannila_expansion_m]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



